export const sidebarLinks = [
  {
    imgURL: "/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/icons/dollar-circle.svg",
    route: "/my-banks",
    label: "My Banks",
  },
  {
    imgURL: "/icons/transaction.svg",
    route: "/transaction-history",
    label: "Transaction History",
  },
  {
    imgURL: "/icons/money-send.svg",
    route: "/payment-transfer",
    label: "Transfer Funds",
  },
];

export const TRANSACTIONS = [
  {
    id: "txn_001",
    $id: "txn_001",
    name: "Starbucks",
    paymentChannel: "in store",
    type: "debit",
    accountId: "acc_001",
    amount: 4.75,
    pending: false,
    category: "Coffee Shops",
    date: "2025-07-01",
    image: "/icons/coffee.svg",
    $createdAt: "2025-06-21T08:23:12.000Z",
    channel: "QR",
    senderBankId: "bank_abc123",
    reveiverBankId: "bank_xyz999",
  },
  {
    id: "txn_002",
    $id: "txn_002",
    name: "Spotify Subscription",
    paymentChannel: "online",
    type: "debit",
    accountId: "acc_001",
    amount: 9.99,
    pending: false,
    category: "Coffee Shops",
    date: "2025-07-01",
    image: "/icons/music.svg",
    $createdAt: "2025-06-20T04:11:05.000Z",
    channel: "Direct Debit",
    senderBankId: "bank_abc123",
    reveiverBankId: "bank_spotify",
  },
  {
    id: "txn_003",
    $id: "txn_003",
    name: "Monthly Salary",
    paymentChannel: "online",
    type: "credit",
    accountId: "acc_001",
    amount: 3200.0,
    pending: false,
    category: "Income",
    date: "2025-06-30",
    image: "/icons/income.svg",
    $createdAt: "2025-06-15T07:45:22.000Z",
    channel: "ACH",
    senderBankId: "bank_employer",
    reveiverBankId: "bank_abc123",
  },
  {
    id: "txn_004",
    $id: "txn_004",
    name: "Electricity Bill",
    paymentChannel: "online",
    type: "debit",
    accountId: "acc_001",
    amount: 110.5,
    pending: true,
    category: "Utilities",
    date: "2025-06-22",
    image: "/icons/electricity.svg",
    $createdAt: "2025-06-22T13:10:45.000Z",
    channel: "Bill Pay",
    senderBankId: "bank_abc123",
    reveiverBankId: "bank_electric",
  },
  {
    id: "txn_005",
    $id: "txn_005",
    name: "Friend Transfer",
    paymentChannel: "online",
    type: "debit",
    accountId: "acc_001",
    amount: 75.0,
    pending: false,
    category: "Transfers",
    date: "2025-06-19",
    image: "/icons/transfer.svg",
    $createdAt: "2025-06-19T17:30:10.000Z",
    channel: "PromptPay",
    senderBankId: "bank_abc123",
    reveiverBankId: "bank_friend123",
  },
  {
    id: "txn_006",
    $id: "txn_006",
    name: "Top-up TrueMoney",
    paymentChannel: "online",
    type: "debit",
    accountId: "acc_001",
    amount: 200.0,
    pending: false,
    category: "Top-up",
    date: "2025-06-18",
    image: "/icons/topup.svg",
    $createdAt: "2025-06-18T10:05:30.000Z",
    channel: "Mobile Banking",
    senderBankId: "bank_abc123",
    reveiverBankId: "bank_truemoney",
  },
];

export const TOP_CATEGORY_STYLES = {
  "Coffee Shops": {
    bg: "bg-pink-25",
    circleBg: "bg-pink-100",
    text: {
      main: "text-pink-900",
      count: "text-pink-700",
    },
    progress: {
      bg: "bg-pink-100",
      indicator: "bg-pink-700",
    },
    icon: "/icons/coins.svg",
  },
  Income: {
    bg: "bg-success-25",
    circleBg: "bg-success-100",
    text: {
      main: "text-success-900",
      count: "text-success-700",
    },
    progress: {
      bg: "bg-success-100",
      indicator: "bg-success-700",
    },
    icon: "/icons/coins.svg",
  },
  Utilities: {
    bg: "bg-indigo-25",
    circleBg: "bg-indigo-100",
    text: {
      main: "text-indigo-900",
      count: "text-indigo-700",
    },
    progress: {
      bg: "bg-indigo-100",
      indicator: "bg-indigo-700",
    },
    icon: "/icons/coins.svg",
  },
  Transfers: {
    bg: "bg-blue-25",
    circleBg: "bg-blue-100",
    text: {
      main: "text-blue-900",
      count: "text-blue-700",
    },
    progress: {
      bg: "bg-blue-100",
      indicator: "bg-blue-700",
    },
    icon: "/icons/coins.svg",
  },
  "Top-up": {
    bg: "bg-yellow-25",
    circleBg: "bg-yellow-100",
    text: {
      main: "text-yellow-900",
      count: "text-yellow-700",
    },
    progress: {
      bg: "bg-yellow-100",
      indicator: "bg-yellow-700",
    },
    icon: "/icons/coins.svg",
  },
  default: {
    bg: "bg-gray-25",
    circleBg: "bg-gray-100",
    text: {
      main: "text-gray-900",
      count: "text-gray-700",
    },
    progress: {
      bg: "bg-blue-100",
      indicator: "bg-blue-700",
    },
    icon: "/icons/shopping-bag.svg",
  },
};

export const TRANSACTIONS_CATEGORY_STYLES = {
  "Coffee Shops": {
    borderColor: "border-pink-600",
    backgroundColor: "bg-pink-500",
    textColor: "text-pink-700",
    chipBackgroundColor: "bg-inherit",
  },
  Payment: {
    borderColor: "border-success-600",
    backgroundColor: "bg-green-600",
    textColor: "text-success-700",
    chipBackgroundColor: "bg-inherit",
  },
  "Bank Fees": {
    borderColor: "border-yellow-600",
    backgroundColor: "bg-yellow-500",
    textColor: "text-yellow-800",
    chipBackgroundColor: "bg-yellow-50",
  },
  Transfer: {
    borderColor: "border-red-700",
    backgroundColor: "bg-red-500",
    textColor: "text-red-500",
    chipBackgroundColor: "bg-red-50",
  },
  Processing: {
    borderColor: "border-[#F2F4F7]",
    backgroundColor: "bg-gray-500",
    textColor: "text-[#344054]",
    chipBackgroundColor: "bg-[#F2F4F7]",
  },
  Success: {
    borderColor: "",
    backgroundColor: "bg-[#12B76A]",
    textColor: "text-[#027A48]",
    chipBackgroundColor: "bg-[#ECFDF3]",
  },
  Travel: {
    borderColor: "border-[#0047AB]",
    backgroundColor: "bg-blue-500",
    textColor: "text-blue-700",
    chipBackgroundColor: "bg-[#ECFDF3]",
  },
  Groceries: {
    borderColor: "border-green-600",
    backgroundColor: "bg-green-500",
    textColor: "text-green-800",
    chipBackgroundColor: "bg-green-50",
  },
  Subscription: {
    borderColor: "border-indigo-600",
    backgroundColor: "bg-indigo-500",
    textColor: "text-indigo-800",
    chipBackgroundColor: "bg-indigo-50",
  },
  Utilities: {
    borderColor: "border-sky-700",
    backgroundColor: "bg-sky-500",
    textColor: "text-sky-800",
    chipBackgroundColor: "bg-sky-50",
  },
  Topup: {
    borderColor: "border-orange-600",
    backgroundColor: "bg-orange-500",
    textColor: "text-orange-800",
    chipBackgroundColor: "bg-orange-50",
  },
  Income: {
    borderColor: "border-emerald-600",
    backgroundColor: "bg-emerald-500",
    textColor: "text-emerald-800",
    chipBackgroundColor: "bg-emerald-50",
  },
  Transportation: {
    borderColor: "border-cyan-700",
    backgroundColor: "bg-cyan-500",
    textColor: "text-cyan-800",
    chipBackgroundColor: "bg-cyan-50",
  },
  Entertainment: {
    borderColor: "border-purple-600",
    backgroundColor: "bg-purple-500",
    textColor: "text-purple-800",
    chipBackgroundColor: "bg-purple-50",
  },
  Refund: {
    borderColor: "border-lime-600",
    backgroundColor: "bg-lime-500",
    textColor: "text-lime-800",
    chipBackgroundColor: "bg-lime-50",
  },
  default: {
    borderColor: "border-blue-500",
    backgroundColor: "bg-blue-500",
    textColor: "text-blue-700",
    chipBackgroundColor: "bg-blue-50",
  },
};
